In [12]:
!pip install seaborn

Requirement already satisfied: seaborn in c:\programdata\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\programdata\anaconda3\lib\site-packages (from seaborn) (2.3.5)
Requirement already satisfied: pandas>=1.2 in c:\programdata\anaconda3\lib\site-packages (from seaborn) (2.3.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\programdata\anaconda3\lib\site-packages (from seaborn) (3.10.6)
Requirement already satisfied: contourpy>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in c:\programdata\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\programdata\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

In [13]:
import seaborn as sns
import matplotlib.pyplot as mp
import numpy as np
import pandas as pd

In [14]:
df = pd.read_csv("data/funnel_data.csv") # relative path - use your actual file path instead of 'data'
df.head()

,session_id,event_type,created_at,browser,traffic_source
0,00007c70-ebd4-4d2b-8e6d-d9149465ee26,product,2021-05-23 04:03:00.000000 UTC,Other,Organic
1,000e0afb-757e-4237-a8cc-6d40c23f6c79,department,2019-09-12 17:47:00.000000 UTC,Chrome,Adwords
2,000e0afb-757e-4237-a8cc-6d40c23f6c79,product,2019-09-12 18:08:00.000000 UTC,Chrome,Adwords
3,000e0afb-757e-4237-a8cc-6d40c23f6c79,cart,2019-09-12 18:36:00.000000 UTC,Chrome,Adwords
4,0018f263-8c98-49f2-9ad9-ffe91b1f7625,product,2022-02-10 12:12:00.000000 UTC,Chrome,Adwords

In [15]:
df.describe()

,session_id,event_type,created_at,browser,traffic_source
count,10605,10605,10605,10605,10605
unique,3000,6,10489,5,5
top,7ead8eb8-0c7e-4210-975d-d1bfe12f250b,product,2024-05-02 02:53:00.000000 UTC,Chrome,Email
freq,13,3721,3,5480,4915

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10605 entries, 0 to 10604
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   session_id      10605 non-null  object
 1   event_type      10605 non-null  object
 2   created_at      10605 non-null  object
 3   browser         10605 non-null  object
 4   traffic_source  10605 non-null  object
dtypes: object(5)
memory usage: 414.4+ KB

In [17]:
df['created_at'] = pd.to_datetime(df['created_at'], utc = True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10605 entries, 0 to 10604
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   session_id      10605 non-null  object
 1   event_type      10605 non-null  object
 2   created_at      10605 non-null  datetime64[ns, UTC]
 3   browser         10605 non-null  object
 4   traffic_source  10605 non-null  object
dtypes: datetime64[ns, UTC](1), object(4)
memory usage: 414.4+ KB

In [18]:
df.sort_values(by = ['session_id', 'created_at'], inplace = True) # sort the dataset by session_id and created_at
df['browser'] = df['browser'].str.strip()
df['traffic_source'] = df['traffic_source'].str.strip()
df.head()

,session_id,event_type,created_at,browser,traffic_source
0,00007c70-ebd4-4d2b-8e6d-d9149465ee26,product,2021-05-23 04:03:00+00:00,Other,Organic
1,000e0afb-757e-4237-a8cc-6d40c23f6c79,department,2019-09-12 17:47:00+00:00,Chrome,Adwords
2,000e0afb-757e-4237-a8cc-6d40c23f6c79,product,2019-09-12 18:08:00+00:00,Chrome,Adwords
3,000e0afb-757e-4237-a8cc-6d40c23f6c79,cart,2019-09-12 18:36:00+00:00,Chrome,Adwords
4,0018f263-8c98-49f2-9ad9-ffe91b1f7625,product,2022-02-10 12:12:00+00:00,Chrome,Adwords

In [19]:
unique_values = df['event_type'].unique()
unique_values

array(['product', 'department', 'cart', 'cancel', 'home', 'purchase'],
      dtype=object)

In [20]:
!pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: pymysql in c:\programdata\anaconda3\lib\site-packages (1.1.3)
Requirement already satisfied: greenlet>=1 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\parth.desktop-5935\appdata\roaming\python\python313\site-packages (from sqlalchemy) (4.14.0)

In [21]:
from sqlalchemy import create_engine

# Users table
users_df = df[['session_id', 'traffic_source', 'browser']].drop_duplicates()

# Events table
events_df = df[['session_id', 'event_type', 'created_at']].copy()

# Adding an event_id column also
events_df.insert(0, 'event_id', range(1, 1 + len(events_df)))

In [22]:
engine = create_engine('mysql+pymysql://root:yourpassword@localhost/ecommerce_funnel')

# df to sql table
users_df.to_sql(name='users', con=engine, if_exists='replace', index=False)
events_df.to_sql(name='events', con=engine, if_exists='replace', index=False)

print("Data successfully loaded into MySQL!")

Data successfully loaded into MySQL!